// <auto-generated />
namespace Base.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrderCategory2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderCategory2));
        
        string IMigrationMetadata.Id
        {
            get { return "201710271727421_OrderCategory2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
