// <auto-generated />
namespace Base.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitBazydanych : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitBazydanych));
        
        string IMigrationMetadata.Id
        {
            get { return "201709251055085_InitBazydanych"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
